spring:
  config:
    activate:
      on-profile: dev
  banner:
    location: dev-banner.txt


  # H2 Driver
  datasource:
    url: jdbc:h2:tcp://localhost/~/growup
    username: sa
    password:
    driver-class-name: org.h2.Driver
